### ISSUE TITLE
Magisk module not enabling and LSposed not recognizing module

### ISSUE THREAD

**Issue by jacob153** [programminghoch10/ClearLineage#3]
I might be doing something wrong here but I have dried multiple times to get this to work with no luck. I'm on a pixel 6 Android 12L. I have LSPosed installed and working properly, I've tested other modules. And the clear lineage module flashed through magisk. In magisk though it shows up greyed out because it is disabled and if I enable it LSPosed still does not recognize (with or without reatart after enabling)

**Comment by programminghoch10** [comment]
Hey there, you're not using LineageOS and thus your setup is not supported officially.
You can join [the telegram group](https://t.me/clearlineage) for workarounds of this problem.
